### ISSUE TITLE
AcquireTokenAsync() throws irregularly System.ExecutionEngineException

### ISSUE THREAD

**Issue by jw8tel** [Azure-Samples/active-directory-dotnet-windows-store#17]
Using Win 10, I sometimes get a System.ExecutionEngineException while trying to run the sample.

It occurs here:
AuthenticationResult result = await authContext.AcquireTokenAsync(resourceId, clientId, redirectURI);

Any pointers?

**Comment by dstrockis** [comment]
If people continue to see this error please let me know!

**Comment by jmprieur** [comment]
Does not seem to be the case at the moment.
