### ISSUE TITLE
New release won't install

### ISSUE THREAD

**Issue by WayPoint7** [Azure-Samples/active-directory-dotnet-windows-store#20]
When installing via NuGet, this is the reaction of the download/installation process:

_Error:     Could not install package 'Microsoft.IdentityModel.Clients.ActiveDirectory 3.10.305231913'. You are trying to install this package into a project that targets  '.NETPortable,Version=v4.6,Profile=Profile32', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author._

Is there a way to get the latest version installed anyhow? What other (older) version is recommended?

**Comment by dstrockis** [comment]
Are you trying to install the package into the sample code, or into your own project?

**Comment by WayPoint7** [comment]
I'm trying to install in a project of my own. That project is a class library (dll) with WIN8.1/Phone 8.1 as targets. In the mean time I have (at least I think I have) succesfully "installed"  by adding the references to Microsoft.IdentityModel.Clients.ActiveDirectory and Microsoft.IdentityModel.Clients.ActiveDirectory.Platform. both in the 3.9.302261508-alpha version. Can you confirm that this is a reliable way to go as well? Is it an option to upgrade to a later version?

**Comment by jmprieur** [comment]
This now was updated with recents ADAL.NET versions. and this works fine.
